<?php

namespace houseBundle\Repository;

/**
 * houseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class houseRepository extends \Doctrine\ORM\EntityRepository
{
}
