<?php

namespace houseBundle\Repository;

/**
 * mediasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mediasRepository extends \Doctrine\ORM\EntityRepository
{
}
